### ISSUE TITLE
iOS Swift version coding.

### ISSUE THREAD

**Issue by GABHISEKBUNTY** [hackiftekhar/IQMediaPickerController#13]
Hey congrats for such a beautiful piece of work. How can I get the image name?

I was thinking to try this code out - 

```
NSURL *refURL = [info valueForKey:UIImagePickerControllerReferenceURL];

    // define the block to call when we get the asset based on the url (below)
    ALAssetsLibraryAssetForURLResultBlock resultblock = ^(ALAsset *imageAsset)
    {
        ALAssetRepresentation *imageRep = [imageAsset defaultRepresentation];
        NSLog(@"[imageRep filename] : %@", [imageRep filename]);
    };

    // get the asset library and fetch the asset based on the ref url (pass in block above)
    ALAssetsLibrary* assetslibrary = [[ALAssetsLibrary alloc] init];
    [assetslibrary assetForURL:refURL resultBlock:resultblock failureBlock:nil];

```

But I need the url for this.

**Comment by hackiftekhar** [comment]
If you selected from library then you'll get `IQMediaAssetURL`, if you captured it using camera then you'll get `IQMediaURL` which is actually a temporary path to recently captured image but it's not the photo library image path since the captured image was never stored to photo library. please check the info dictionary and find where exactly you are getting these info.
